services:
  db:
    image: postgres:16
    container_name: order_inventory_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_inventory
    ports:
      - "5432:5432"
    volumes:
      - order_inventory_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

volumes:
  order_inventory_data:
